# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: 
      - '**'
      # '!branch' <- to exlude your branch
  pull_request:
    branches: 
      - '**'


permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install selenium
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        sudo apt install ffmpeg
    - name: Set up environment variables
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    - name: Test with pytest
      run: |
        pytest tests/tests.py
        pytest tests/tests_flask.py
    - name: Start Flask Server
      run: |
        nohup python setup.py > server.log &
        sleep 5
        cat server.log
    - name: Test with selenium
      run: |
        pytest tests/E2E.py
